"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = "helix"

format = '''
╭─ $directory$git_branch$python
╰─ $character'''

[character]
success_symbol = "[](lilac)"
error_symbol = "[](apricot)"

[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
style = 'fg:#FFFFFF'

[git_branch]
format = '[](revolver)[$symbol$branch(:$remote_branch)]($style)[](revolver) '
symbol = ' '
style = 'bg:revolver fg:lilac'

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = '6'
staged = ' '
conflicted = ' '
untracked = ' '
ahead = ''
modified = ' '
deleted = ' '

[fill]
symbol = '─'
style = '1'

[time]
disabled = false
format = '[󰥔 $time]($style)'
style = 'white'

[python]
format = '[](bossanova)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[](bossanova)'
symbol = " "
style = "bg:bossanova fg:mint"

[palettes.helix]
revolver = "#281733"
bossanova = "#452859"
lilac = "#dbbfef"
comet = "#5a5977"
white = "#ffffff"
apricot = "#f47868"
mint = "#9ff28f"
