"$schema" = 'https://starship.rs/config-schema.json'


format = '''
[╭─](248) $directory$git_branch$git_status$fill $time
[╰─](248)  '''

[directory]
style = 'white'

[git_branch]
symbol = ' '
style = 'green'

[git_status]
style = 'red'

[fill]
symbol = '─'
style = '248'

[time]
disabled = false
format = '[󰥔 $time]($style)'
style = 'white'

[character] 
success_symbol = '[➜](bold green)'


