"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '''
╭─ $directory$git_branch$git_status$fill
╰─  '''

[directory]
style = 'white'

[git_branch]
format='[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = 'green'

[git_status]
style = 'red'

[fill]
symbol = '─'
style = '249'

[time]
disabled = false
format = '[󰥔 $time]($style)'
style = 'white'

[character] 
success_symbol = '[➜](bold green)'


