"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
╭─ $directory$git_branch$python
╰─ $character'''

[character]
success_symbol = "[](#ffffff)"
error_symbol = "[](#ff565f)"

[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
style = 'fg:#FFFFFF'

[git_branch]
format = '[](#1f1f1f)[$symbol$branch(:$remote_branch)]($style)[](#1f1f1f) '
symbol = ' '
style = 'bg:#1f1f1f fg:#ededed'

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = '6'
staged = ' '
conflicted = ' '
untracked = ' '
ahead = ''
modified = ' '
deleted = ' '

[fill]
symbol = '─'
style = '1'

[time]
disabled = false
format = '[󰥔 $time]($style)'
style = 'white'

[python]
format = '[](#0B2211)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[](#0B2211)'
symbol = " "
style = "bg:#0B2211 fg:#00ca50"
