"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
╭─ $directory$git_branch
╰─ [](15) '''

[directory]
style = '15 bold'

[git_branch]
format='[](#1e1e1e)[$symbol$branch(:$remote_branch)]($style)[](#1e1e1e) '
symbol = ' '
style = 'bg:#1e1e1e fg:#ababab'

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = '6'
staged = ' '
conflicted = ' '
untracked = ' '
ahead = ''
modified = ' '
deleted = ' '

[fill]
symbol = '─'
style = '1'

[time]
disabled = false
format = '[󰥔 $time]($style)'
style = 'white'

[character] 
success_symbol = '[➜](bold green)'


