"$schema" = 'https://starship.rs/config-schema.json'


format = '''
╭─ $directory$git_branch$git_status$fill $time
╰─  '''

[directory]
style = 'white'

[git_branch]
symbol = ' '
style = 'green'

[git_status]
style = 'red'

[fill]
symbol = '─'
style = 'white'

[time]
disabled = false
format = '[󰥔 $time]($style)'
style = 'white'

[character] 
success_symbol = '[➜](bold green)'


