"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
[╭─](1) $directory$git_branch$git_status
[╰─](1) [](7) '''

[directory]
style = '7 bold'

[git_branch]
format='[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = '5'

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = '6'
staged = ' '
conflicted = ' '
untracked = ' '
ahead = ''
modified = ' '

[fill]
symbol = '─'
style = '1'

[time]
disabled = false
format = '[󰥔 $time]($style)'
style = 'white'

[character] 
success_symbol = '[➜](bold green)'


